/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/sidebar-tail/actions.vue')['default']
    AddConversation: typeof import('./src/components/sidebar-tail/add-conversation.vue')['default']
    ConversationItem: typeof import('./src/components/conversation-item/conversation-item.vue')['default']
    Mask: typeof import('./src/components/gpt-mask/mask.vue')['default']
    Plugins: typeof import('./src/components/gpt-plugins/plugins.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
